name: Build APK
on:
  push:
    branches: [main, master]
  workflow_dispatch:
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Buildozer Engine
      uses: ArtemGovorov/buildozer-action@v1
      with:
        command: buildozer android debug --no-compile-json
        repository_root: .
    - uses: actions/upload-artifact@v4
      with:
        name: Smart-Khata-App
        path: bin/*.apk
